name: comicslate
description: Official client application for https://comicslate.org/

# Version information is set by Fastlane when building:
# $ flutter build --build-name=... --build-number=...
# We set a default here for debugging purposes because debug binary is not
# usually built via Fastlane.
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  built_value:
  cached_network_image:
  device_info:
  firebase_analytics:
  flutter:
    sdk: flutter
  flutter_cache_manager:
  flutter_localizations:
    sdk: flutter
  flutter_sentry:
  http: any
  intl:
  package_info:
  provider:
  quiver:
  share:
  shared_preferences:
  url_launcher:
  wakelock:

dev_dependencies:
  build_runner:
  built_value_generator:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test:

flutter:
  uses-material-design: true

  fonts:
    - family: DatFestComic
      fonts:
        - asset: fonts/dat_fest.ttf

  assets:
    - images/logo0.webp
    - images/logo1.webp
    - images/logo2.webp
    - images/logo3.webp
    - images/logo4.webp
    - images/logo5.webp
    - images/logo6.webp
    - images/logo7.webp
    - images/logo8.webp
    - images/favicon.webp
